Adapt foreground style
pixiv/charcoal-ios pull request #108
Opened 2023-08-09 07:24 UTC by kevinneko

## 解決したいこと
- SwiftUIでforegroundColorが使われているところがあるが、deprecatedなはずなのでforegroundStyleに置き換えたい

## やったこと
- 解決したいこと

## やらないこと
- None

## スクリーンショット
UIに変更が生じた場合はスクショを貼ってください

Before | After
---|---

## 動作確認環境
- iOS 13 - iOS 17

2023-08-09 07:25 UTC, kevinneko commented
CIシステムを一時的に使用できないため、iOS 13からiOS 17のシミュレーターで手動でチェックしましたが、問題は見つかりませんでした。

foregroundStyleは最低iOS 15からサポートされているので、CharcoalForegroundColor ViewModifierを導入して互換性を処理しました。

foregroundStyleはより先進的なShapeStyleプロトコルをサポートしていますが、現在その需要はないようですので、互換性は行っていません。

2023-08-09 10:26 UTC, kvvzr requested changes

2023-08-09 10:26 UTC, kvvzr commented on Sources/Charcoal/SwiftUI/Colors/OnSurfaces.swift
> +public extension View {
[MUST] ライブラリの外でcharcoalForegroundColorを使ってもらうことは難しいと思っていて、foregroundStyleの適用はライブラリの中だけでできていれば良いと思います。なので、publicは外していただければ！

またextensionを置く場所ですが、OnSurfaces以外のところからも使うと思うので `Charcoal/SwiftUI` 以下に `Extensions` ディレクトリを作っておくと良いのかなと思いました。

2023-08-09 10:26 UTC, kvvzr commented on Sources/Charcoal/SwiftUI/Colors/OnSurfaces.swift
> +    func charcoalForegroundColor(_ color: Color) -> some View {
[IMO] このメソッド名もライブラリの外から使われるものでないのと、iOS 15未満で使えるようにするためのものなので、 `foregroundStyle(_ color: Color)` のようにしてiOS 15未満でも標準のforegroundStyleと同じようにするのが良いかと思いました。

2023-08-15 04:12 UTC, kevinneko commented on Sources/Charcoal/SwiftUI/Colors/OnSurfaces.swift
> +    func charcoalForegroundColor(_ color: Color) -> some View {
`foregroundStyle`と`foregroundColor`はどちらも SwiftUI で既に存在する System API ですので、私はカスタム API には全て`charcoal` を付けることを提案します。これにより、衝突を避けつつ、API の出所を一目で確認できるようになります。

2023-08-15 04:24 UTC, kvvzr commented on Sources/Charcoal/SwiftUI/Colors/OnSurfaces.swift
> +    func charcoalForegroundColor(_ color: Color) -> some View {
それもわかります。 一方で `charcoal~` は外から使われるAPIにつけている名前なので、公開されているmodifierと勘違いしそうな気もするんですよね。

例えば、 `backportForegroundStyle` などとするのはどう思いますか?

ちょっと調べて見つけたんですが、 https://github.com/shaps80/SwiftUIBackports だと `.backport.presentationDetents([.medium, .large])` みたいなnamespaceを生やしているっぽい

2023-08-15 05:10 UTC, kevinneko commented on Sources/Charcoal/SwiftUI/Colors/OnSurfaces.swift
> +    func charcoalForegroundColor(_ color: Color) -> some View {
ご指摘いただき、APIの公開状況を区別することは確かに非常に重要です。新しい実装としてBackportを採用しましたので、ご確認をお願いいたします。

2023-08-15 05:28 UTC, kvvzr approved these changes
.backportで使えるようにするのとても良さそうです〜 🎉

2023-08-15 08:27 UTC, merged