Feat UIKit Toast
pixiv/charcoal-ios pull request #250
Opened 2024-07-23 07:46 UTC by kevinneko

## 解決したいこと
https://github.com/user-attachments/assets/d1c29e56-3fd5-41ef-bd2e-f5d22f23132e

## 動作確認環境
iOS 15 - iOS 17

2024-07-24 08:57 UTC, kvvzr requested changes

2024-07-24 08:57 UTC, kvvzr commented on CharcoalUIKitSample/Sources/CharcoalUIKitSample/Views/Toasts/Toasts.swift
> +enum ToastsTitles: String, CaseIterable {
SwiftUIの方とCatalogの内容が違っているのが少し気になっています。
SwiftUIでもUIKitでも同じ見た目にできることが重要なので、Catalogの並び順や内容もできるだけ揃えて置けると良いなと思います

2024-07-24 08:57 UTC, kvvzr commented on Sources/CharcoalUIKit/Components/Toast/CharcoalSnackBar.swift
> +        let toastView = CharcoalSnackBarView(text: text, thumbnailImage: thumbnailImage, maxWidth: maxWidth, action: action)
わかりやすさのため、toastView→snackbarViewにしたいです

2024-07-24 08:57 UTC, kvvzr commented on Sources/CharcoalUIKit/Components/Toast/CharcoalRubberGesture.swift
> +class CharcoalRubberGesture: NSObject, CharcoalGesture {
これはジェスチャーというより、ジェスチャーの結果を受けた結果良い感じにアニメーションするものなので、ジェスチャーという名前は正しくなさそうな気がしました。

このclassの名前をCharcoalRubberAnimatorとかの命名に変えつつ、PanGestureRecognizerは外側のViewで作ってあげて、addGestureRecognizerにこのclassのhandlePan(:)を渡すのはどうでしょうか...?

2024-07-24 08:57 UTC, kvvzr commented on Sources/CharcoalShared/Extensions/UIColor+Extension.swift
> +public extension UIColor {
Sharedに置いてpublicにするとライブラリ以外からでもアクセスできるようになってしまうので、そうなってしまうよりかはCharcoalSwiftUI / CharcoalUIKitそれぞれに定義する方を好みます

2024-08-07 01:04 UTC, kvvzr requested changes

2024-08-07 01:04 UTC, kvvzr commented on Sources/CharcoalUIKit/Components/Toast/CharcoalRubberAnimator.swift
> +        print("CharcoalRubberAnimator deinit")
このdeinitはデバッグ用な気がするので消したいです〜

2024-08-07 04:57 UTC, kevinneko commented on Sources/CharcoalUIKit/Components/Toast/CharcoalRubberAnimator.swift
> +        print("CharcoalRubberAnimator deinit")
ああ、削除するのを忘れてしまいました

2024-08-07 06:36 UTC, kvvzr approved these changes

2024-08-07 07:24 UTC, merged